#+BEGIN_EXAMPLE
 ______  __                       __
/\  _  \/\ \                     /\ \__      /'\_/`\
\ \ \L\ \ \ \____    ___   __  __\ \ ,_\    /\      \
 \ \  __ \ \ '__`\  / __`\/\ \/\ \\ \ \/    \ \ \__\ \  /'__`\
  \ \ \/\ \ \ \L\ \/\ \L\ \ \ \_\ \\ \ \_    \ \ \_/\ \/\  __/
   \ \_\ \_\ \_,__/\ \____/\ \____/ \ \__\    \ \_\\ \_\ \____\
    \/_/\/_/\/___/  \/___/  \/___/   \/__/     \/_/ \/_/\/____/
#+END_EXAMPLE
* Bio
  Hello there! My name's Joe, and online I go by Doge(OfDisaster). I am a
  3rd-year Computer Science and Engineering student.

* Hobbies
  Two of my biggest interests revolve around the computer: programming and video
  games. However, I also enjoy listening to music and photography.

** Coding
   If I'm not doing schoolwork, I'm usually coding or doing other Computer
   Science related things. Right now, I mostly just have one main project: a
   Discord bot called [[https://github.com/Joe-Downs/coloriz][COLOR*IZ]]. In brief, it allows regular users to assign
   their own custom colors - without needing an admin to make dedicated color
   roles beforehand.

*** Tools
    For everything related to coding, I use [[https://www.gnu.org/software/emacs/][GNU Emacs]]. Frankly, it's
    amazing. The amount of stuff it can do is mind-boggling, and I don't even
    use probably half of that! "Feature creep," you say? Maybe. However, it is
    the best operating system, but could use a nice text editor.

    In all seriousness, its customizability is outstanding. With sites like
    [[https://melpa.org/][MELPA]], you can find packages for nearly anything. From games to git
    porcelains - like [[https://melpa.org/#/magit][Magit]]. Magit... That's gotta be the coolest thing I've
    seen recently. I started (and did) all my git stuff on the commandline, but
    doing it right in Emacs is just *so nice*. If you use Emacs and haven't used
    it, I highly recommend it.

    If you haven't heard of Emacs before, I highly suggest checking it out. It
    may not be as fancy as Visual Studio, but in my opinion it is much easier to
    use and customize. And best of all: it's *FOSS*. I'm a big believer in
    FOSS. Not only is it cheaper than alternatives, it can often be better -
    both privacy-wise and performance / features.

** Gaming
   Some games I enjoy playing:
   - Team Fortress 2
   - Minecraft
   - Slime Rancher
   - Stardew Valley
   - Portal 2
   - ...and many more!
   - [[https://steamcommunity.com/id/dogeofdisaster][My Steam profile!]]

* My Other Links
  To be filled...

