#+BEGIN_EXAMPLE
 _______________________________________________________________________
/  __      __          ___                                      __      \
| /\ \  __/\ \        /\_ \                                    /\ \     |
| \ \ \/\ \ \ \     __\//\ \     ___    ___     ___ ___      __\ \ \    |
|  \ \ \ \ \ \ \  /'__`\\ \ \   /'___\ / __`\ /' __` __`\  /'__`\ \ \   |
|   \ \ \_/ \_\ \/\  __/ \_\ \_/\ \__//\ \L\ \/\ \/\ \/\ \/\  __/\ \_\  |
|    \ `\___x___/\ \____\/\____\ \____\ \____/\ \_\ \_\ \_\ \____\\/\_\ |
|     '\/__//__/  \/____/\/____/\/____/\/___/  \/_/\/_/\/_/\/____/ \/_/ |
\         ______________________________________________________________/
  \      /
    \  /
      \ .--.
       |o_o |
       |:_/ |
      //   \ \
     (|     | )
    /'\_   _/`\
    \___)=(___/
#+END_EXAMPLE

* Welcome to my Website!
  A friend of mine introduced me to Gemini and it's really neat! ([[gemini://gemini.gogobe.be][This site is
  in Gemini]]) I've had lots of fun tinkering with it. It spurred me on to
  actually populate my HTTP website, so she gets a huge shoutout. (Hi Mallow!
  <3)

My favorite things:
- Mallow
[[gemini://tsuntsun.cities.yesterweb.org/][Her Gemini site]]
[[https://portal.mozz.us/gemini/tsuntsun.cities.yesterweb.org][HTTP Mirror]]
- Cuties (See Above)

** Directory
- [[about.md][About Me]]
- [[tao.md][The Tao of Programming]]

** About This Site
*** What the heck is that name?
    My domain is meant to be read as one word: gogobebe. It's a reference to a
    KPop song by the girl group MAMAMOO. It's title being... "[[https://youtu.be/Cp56JdkmE9s][gogobebe]]" (I
    highly recommend it!) I usually pronounce my domain just as it's said in the
    song.

*** What does it run on?
    It is a cloud instance running [[https://ubuntu.com/][Ubuntu 21.10]]. My site operates as both a
    'regular' HTTP website and a Gemini capsule. For my Gemini server, I went
    with [[https://tildegit.org/solderpunk/molly-brown][molly-brown]] because it was recommended by others. It's the only one
    I've used, but so far it's working well enough. (Fingers crossed!) As for
    HTTP, I use good ol' [[https://httpd.apache.org/][Apache]] because that's what I have the most exposure to.

[[tao.md][Thus spake the Master Programmer: "Time for you to leave."]]
