#+BEGIN_EXAMPLE
 ____________________________________________
/  _    _      _                          _  \
| | |  | |    | |                        | | |
| | |  | | ___| | ___ ___  _ __ ___   ___| | |
| | |/\| |/ _ \ |/ __/ _ \| '_ ` _ \ / _ \ | |
| \  /\  /  __/ | (_| (_) | | | | | |  __/_| |
|  \/  \/ \___|_|\___\___/|_| |_| |_|\___(_) |
\__   _______________________________________/
   \ /
    \
        .--.
       |o_o |
       |:_/ |
      //   \ \
     (|     | )
    /'\_   _/`\
    \___)=(___/
#+END_EXAMPLE

* Hi! Hallo! Annyeong! Hei! Olá!
  Welcome to my little corner of the [[https://xkcd.com/181/][blagoblag]]! A friend of mine introduced me
  to Gemini and it's really neat! ([[gemini://gemini.gogobe.be][This site is in Gemini]]) I've had lots of fun
  tinkering with it. It spurred me on to actually populate my HTTP website, so
  she gets a huge shoutout. (Hi Mallow!  <3)

  (Yes, I know it's Romanized and not Hangul. Unfortunately, the Hangul is not
  the same width as the rest of my monospace characters, and I just couldn't
  with that, man... Maybe I'll be able to fix it later.)

My favorite things:
- Mallow
[[gemini://tsuntsun.cities.yesterweb.org/][Her Gemini site]]
[[https://portal.mozz.us/gemini/tsuntsun.cities.yesterweb.org][HTTP Mirror]]
- Cuties (See Above)

** Directory
- [[./about.org][About Me]]
- [[./tao.org][The Tao of Programming]]
- [[./recipes/index.org][Recipes]]

** About This Site
*** What the heck is that name?
    My domain is meant to be read as one word: gogobebe. It's a reference to a
    KPop song by the girl group MAMAMOO. Its title being... "[[https://youtu.be/Cp56JdkmE9s][gogobebe]]" (I highly
    recommend it!) I usually pronounce my domain just as it's said in the song.

*** What does it run on?
    It is a cloud instance running [[https://ubuntu.com/][Ubuntu 21.10]]. My site operates as both a
    'regular' HTTP website and a Gemini capsule. For my Gemini server, I went
    with [[https://tildegit.org/solderpunk/molly-brown][molly-brown]] because it was recommended by others. It's the only one
    I've used, but so far it's working well enough. (Fingers crossed!) As for
    HTTP, I use good ol' [[https://httpd.apache.org/][Apache]] because that's what I have the most exposure to.

[[./tao.org][Thus spake the Master Programmer: "Time for you to leave."]]
